--- #YAML:1.0
name:                CFPlus
version:             0.995
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    AnyEvent:                      0
    BerkeleyDB:                    0.27
    Compress::LZF:                 1.6
    Crossfire:                     1.1
    Event:                         1.07
    JSON::XS:                      1.5
    LWP:                           0
    Pod::POM:                      0.15
    Time::HiRes:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
